# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mauricio Vera
email: veramauricio92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My little brain dump blog.
  Built with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mauriciv.github.io" # the base hostname & protocol for your site
twitter_username: mauricioverab
github_username:  mauriciv

# Build settings
markdown: kramdown
